esphome:
  name: esp-fan-dual
  friendly_name: ESP Fan Dual Zone

esp32:
  board: esp32-s3-devkitc-1
  framework:
    type: esp-idf

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "GXuwx9Eh7Jr9+Ftj90jDXDfkYIWw9fQ77Si5HCQ94m8=" # À changer pour la sécurité

ota:
  - platform: esphome

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  ap:
    ssid: "Esp-Fan-Dual Fallback"
    password: !secret wifi_password

captive_portal:

web_server:
  port: 80

# --- SORTIES PWM ---
output:
  - platform: ledc
    pin: GPIO6
    id: pwm_line_1
    frequency: 25000 Hz
  - platform: ledc
    pin: GPIO5 # Seconde ligne
    id: pwm_line_2
    frequency: 25000 Hz

# --- CAPTEURS ---
sensor:
  # Ligne 1 - Tachymètre
  - platform: pulse_counter
    pin: 
      number: GPIO4
      mode: {input: true, pullup: true}
    name: "Vitesse Ligne 1"
    unit_of_measurement: 'RPM'
    id: speed_line_1
    filters:
      - lambda: return x / 2.0;
    update_interval: 3s
  
  # Ligne 2 - Tachymètre
  - platform: pulse_counter
    pin: 
      number: GPIO18 # Seconde ligne
      mode: {input: true, pullup: true}
    name: "Vitesse Ligne 2"
    unit_of_measurement: 'RPM'
    id: speed_line_2
    filters:
      - lambda: return x / 2.0;
    update_interval: 3s

  # Capteur DHT22 - Ligne 1
  - platform: dht
    pin: GPIO7
    model: DHT22
    temperature:
      name: "Température Ligne 1"
      id: temp_1
      on_value:
        then:
          - lambda: |-
              if (id(auto_mode_1).state) {
                float temp = x;
                int speed = 0;
                if (temp < 20) speed = 0;
                else if (temp < 25) speed = 25;
                else if (temp < 30) speed = 50;
                else if (temp < 35) speed = 75;
                else speed = 100;

                if (speed == 0) { id(fan_1).turn_off().perform(); }
                else { id(fan_1).turn_on().set_speed(speed).perform(); }
              }
    humidity:
      name: "Humidité Ligne 1"
    update_interval: 30s

  # Capteur DHT22 - Ligne 2
  - platform: dht
    pin: GPIO8 # Seconde ligne
    model: DHT22
    temperature:
      name: "Température Ligne 2"
      id: temp_2
      on_value:
        then:
          - lambda: |-
              if (id(auto_mode_2).state) {
                float temp = x;
                int speed = 0;
                if (temp < 20) speed = 0;
                else if (temp < 25) speed = 25;
                else if (temp < 30) speed = 50;
                else if (temp < 35) speed = 75;
                else speed = 100;

                if (speed == 0) { id(fan_2).turn_off().perform(); }
                else { id(fan_2).turn_on().set_speed(speed).perform(); }
              }
    humidity:
      name: "Humidité Ligne 2"
    update_interval: 30s

# --- VENTILATEURS ---
fan:
  - platform: speed
    output: pwm_line_1
    name: "Ventilateurs Ligne 1"
    id: fan_1
    speed_count: 100
  - platform: speed
    output: pwm_line_2
    name: "Ventilateurs Ligne 2"
    id: fan_2
    speed_count: 100

# --- CONTRÔLES MANUELS ---
number:
  - platform: template
    name: "Vitesse Manuelle L1"
    id: manual_speed_1
    min_value: 0
    max_value: 100
    step: 5
    unit_of_measurement: "%"
    mode: slider
    set_action:
      then:
        - if:
            condition: {lambda: 'return x == 0;'}
            then: [- fan.turn_off: fan_1]
            else: [- fan.turn_on: {id: fan_1, speed: !lambda 'return int(x);'}]
    lambda: "return id(fan_1).state ? id(fan_1).speed * 100 : 0;"

  - platform: template
    name: "Vitesse Manuelle L2"
    id: manual_speed_2
    min_value: 0
    max_value: 100
    step: 5
    unit_of_measurement: "%"
    mode: slider
    set_action:
      then:
        - if:
            condition: {lambda: 'return x == 0;'}
            then: [- fan.turn_off: fan_2]
            else: [- fan.turn_on: {id: fan_2, speed: !lambda 'return int(x);'}]
    lambda: "return id(fan_2).state ? id(fan_2).speed * 100 : 0;"

# --- SWITCHES MODES ---
switch:
  - platform: template
    name: "Mode Auto Ligne 1"
    id: auto_mode_1
    optimistic: true
    restore_mode: RESTORE_DEFAULT_ON
    icon: "mdi:thermostat-auto"
  - platform: template
    name: "Mode Auto Ligne 2"
    id: auto_mode_2
    optimistic: true
    restore_mode: RESTORE_DEFAULT_ON
    icon: "mdi:thermostat-auto"
