substitutions:
  name: "esp-fan"
  friendly_name: "Ventilation Baie"
  # Variables pour .base.yaml
  board: esp32-s3-devkitc-1
  type: esp-idf
  loglevel: INFO
  static_ip: 192.168.1.123 # <-- ADRESSE IP À DÉFINIR ICI

packages:
  base: !include .base.yaml

# Enable Home Assistant API
api:
  encryption:
    key: "GXuwx9Eh7Jr9+Ftj90jDXDfkYIWw9fQ77Si5HCQ94m8="

# --- MATÉRIEL : SORTIES PWM (Haut & Bas) ---
output:
  # Ligne 1 (Haut) - GPIO6
  - platform: ledc
    pin: GPIO6
    id: pwm_line_1
    frequency: 25000 Hz
    min_power: 0.0
    max_power: 1.0

  # Ligne 2 (Bas) - GPIO35
  - platform: ledc
    pin: GPIO35
    id: pwm_line_2
    frequency: 25000 Hz
    min_power: 0.0
    max_power: 1.0

# --- MATÉRIEL : CAPTEURS (RPM & Temp) ---
sensor:
  # Ligne 1 - Tachymètre (GPIO4)
  - platform: pulse_counter
    pin: 
      number: GPIO4
      mode: {input: true, pullup: true}
    name: "Vitesse Ligne 1"
    unit_of_measurement: 'RPM'
    id: speed_line_1
    filters: [{lambda: return x / 2.0;}]
    update_interval: 3s
  
  # Ligne 1 - DHT22 (GPIO7)
  - platform: dht
    pin: GPIO7
    model: DHT22
    temperature:
      name: "Température Ligne 1"
      id: temp_1
      on_value:
        then: [script.execute: update_ventilation]
    update_interval: 5s

  # Puissance Ventilateur L1 (%)
  - platform: template
    name: "Puissance Ventilateur L1"
    unit_of_measurement: "%"
    icon: "mdi:percent"
    accuracy_decimals: 0
    lambda: |-
      return id(fan_1).state ? id(fan_1).speed : 0;
    update_interval: 5s

  # Ligne 2 - Tachymètre (GPIO36)
  - platform: pulse_counter
    pin: 
      number: GPIO36
      mode: {input: true, pullup: true}
    name: "Vitesse Ligne 2"
    unit_of_measurement: 'RPM'
    id: speed_line_2
    filters: [{lambda: return x / 2.0;}]
    update_interval: 3s

  # Ligne 2 - DHT22 (GPIO37)
  - platform: dht
    pin: GPIO37
    model: DHT22
    temperature:
      name: "Température Ligne 2"
      id: temp_2
      on_value:
        then: [script.execute: update_ventilation]
    update_interval: 5s

  # Puissance Ventilateur L2 (%)
  - platform: template
    name: "Puissance Ventilateur L2"
    unit_of_measurement: "%"
    icon: "mdi:percent"
    accuracy_decimals: 0
    lambda: |-
      return id(fan_2).state ? id(fan_2).speed : 0;
    update_interval: 5s

# --- CONFIGURATION VENTILATEURS ---
fan:
  - platform: speed
    output: pwm_line_1
    name: "Ventilateurs Ligne 1"
    id: fan_1
    speed_count: 100

  - platform: speed
    output: pwm_line_2
    name: "Ventilateurs Ligne 2"
    id: fan_2
    speed_count: 100

# --- VARIABLES GLOBALES (Consignes Partagées) ---
number:
  # Consigne MIN (Partagée)
  - platform: template
    name: "Consigne Temp Min"
    id: global_temp_min
    min_value: 15
    max_value: 35
    step: 1
    unit_of_measurement: "°C"
    mode: box
    icon: "mdi:thermometer-low"
    optimistic: true
    restore_value: true
    initial_value: 25
    set_action:
      then:
        - lambda: 'id(global_temp_min).publish_state(x);'
        - script.execute: update_ventilation

  # Consigne MAX (Partagée)
  - platform: template
    name: "Consigne Temp Max"
    id: global_temp_max
    min_value: 25
    max_value: 50
    step: 1
    unit_of_measurement: "°C"
    mode: box
    icon: "mdi:thermometer-high"
    optimistic: true
    restore_value: true
    initial_value: 35
    set_action:
      then:
        - lambda: 'id(global_temp_max).publish_state(x);'
        - script.execute: update_ventilation

  # Durée Boost
  - platform: template
    name: "Durée Boost"
    id: boost_duration
    min_value: 1
    max_value: 60
    step: 1
    unit_of_measurement: "min"
    mode: box
    icon: "mdi:timer-outline"
    optimistic: true
    restore_value: true
    initial_value: 10
    
  # --- SLIDERS MANUELS ---
  - platform: template
    name: "Vitesse Manuelle L1"
    id: manual_speed_1
    min_value: 0
    max_value: 100
    step: 5
    unit_of_measurement: "%"
    mode: slider
    icon: "mdi:fan"
    set_action:
      then:
        - lambda: 'id(auto_mode_1).turn_off();' # Coupe l'auto L1 uniquement
        - if:
            condition:
              lambda: 'return x == 0;'
            then:
              - fan.turn_off: fan_1
            else:
              - fan.turn_on: 
                  id: fan_1 
                  speed: !lambda 'return int(x);'
    lambda: "return id(fan_1).state ? id(fan_1).speed : 0;"

  - platform: template
    name: "Vitesse Manuelle L2"
    id: manual_speed_2
    min_value: 0
    max_value: 100
    step: 5
    unit_of_measurement: "%"
    mode: slider
    icon: "mdi:fan"
    set_action:
      then:
        - lambda: 'id(auto_mode_2).turn_off();' # Coupe l'auto L2 uniquement
        - if:
            condition:
              lambda: 'return x == 0;'
            then:
              - fan.turn_off: fan_2
            else:
              - fan.turn_on:
                  id: fan_2
                  speed: !lambda 'return int(x);'
    lambda: "return id(fan_2).state ? id(fan_2).speed : 0;"

# --- ALERTES SÉCURITÉ ---
binary_sensor:
  - platform: template
    name: "Alerte Capteur L1"
    id: alert_l1
    device_class: problem
    icon: "mdi:alert-circle"
  
  - platform: template
    name: "Alerte Capteur L2"
    id: alert_l2
    device_class: problem
    icon: "mdi:alert-circle"

  - platform: template
    name: "Alerte Surchauffe (Interlock)"
    id: alert_interlock
    device_class: heat
    icon: "mdi:fire-alert"

# --- SWITCHES MODES ---
switch:
  # BOOST GLOBAL
  - platform: template
    name: "Mode Boost"
    id: boost_mode
    optimistic: true
    icon: "mdi:rocket-launch"
    turn_on_action:
      - logger.log: "🚀 BOOST ACTIF (Global)"
      - script.execute: update_ventilation # Le script appliquera 100%
      - delay: !lambda 'return id(boost_duration).state * 60000;'
      - switch.turn_off: boost_mode
    turn_off_action:
      - logger.log: "Fin du Boost"
      - script.execute: update_ventilation

  # Auto Mode Ligne 1
  - platform: template
    name: "Mode Auto Ligne 1"
    id: auto_mode_1
    optimistic: true
    restore_mode: RESTORE_DEFAULT_ON
    icon: "mdi:thermostat-auto"
    turn_on_action:
      - script.execute: update_ventilation
    turn_off_action:
      - logger.log: "Mode Auto L1 désactivé"

  # Auto Mode Ligne 2
  - platform: template
    name: "Mode Auto Ligne 2"
    id: auto_mode_2
    optimistic: true
    restore_mode: RESTORE_DEFAULT_ON
    icon: "mdi:thermostat-auto"
    turn_on_action:
      - script.execute: update_ventilation
    turn_off_action:
      - logger.log: "Mode Auto L2 désactivé"

# --- LOGIQUE INTELLIGENTE ---
script:
  - id: update_ventilation
    mode: restart
    then:
      - lambda: |-
          // 1. Gestion BOOST (Priorité Absolue)
          if (id(boost_mode).state) {
            id(fan_1).turn_on().set_speed(100).perform();
            id(fan_2).turn_on().set_speed(100).perform();
            return;
          }

          // Variables Températures
          float t1 = id(temp_1).state;
          float t2 = id(temp_2).state;
          bool t1_valid = !std::isnan(t1);
          bool t2_valid = !std::isnan(t2);

          // Variables Consignes
          float t_min = id(global_temp_min).state;
          float t_max = id(global_temp_max).state;
          float t_crit = t_max + 5.0; // Interlock dynamique
          bool interlock = false;

          // 2. Gestion INTERLOCK (Surchauffe Critique)
          // Si l'une des zones dépasse le seuil critique, tout à fond !
          if ((t1_valid && t1 >= t_crit) || (t2_valid && t2 >= t_crit)) {
            interlock = true;
          }
          id(alert_interlock).publish_state(interlock);

          if (interlock) {
            ESP_LOGW("safety", "SURCHAUFFE CRITIQUE ! Activation Interlock (100%)");
            id(fan_1).turn_on().set_speed(100).perform();
            id(fan_2).turn_on().set_speed(100).perform();
            return;
          }

          // 3. Calcul LIGNE 1
          if (id(auto_mode_1).state) {
            int speed1 = 0;
            if (!t1_valid) {
              // Fail-Safe L1
              speed1 = 50; 
              id(alert_l1).publish_state(true);
              ESP_LOGW("safety", "Erreur Capteur L1 -> Fail-Safe 50%");
            } else {
              id(alert_l1).publish_state(false);
              // Courbe Linéaire L1
              if (t1 < t_min) speed1 = 0;
              else if (t1 >= t_max) speed1 = 100;
              else speed1 = (int)(((t1 - t_min) / (t_max - t_min)) * 100);
            }

            // Application L1 (avec Kickstart si démarrage)
            if (speed1 == 0) {
              if (id(fan_1).state) id(fan_1).turn_off().perform();
            } else {
              if (!id(fan_1).state) { 
                // Kickstart
                id(fan_1).turn_on().set_speed(50).perform();
                delay(1000); 
              }
              id(fan_1).turn_on().set_speed(speed1).perform();
            }
          }

          // 4. Calcul LIGNE 2
          if (id(auto_mode_2).state) {
            int speed2 = 0;
            if (!t2_valid) {
              // Fail-Safe L2
              speed2 = 50;
              id(alert_l2).publish_state(true);
              ESP_LOGW("safety", "Erreur Capteur L2 -> Fail-Safe 50%");
            } else {
              id(alert_l2).publish_state(false);
              // Courbe Linéaire L2
              if (t2 < t_min) speed2 = 0;
              else if (t2 >= t_max) speed2 = 100;
              else speed2 = (int)(((t2 - t_min) / (t_max - t_min)) * 100);
            }

            // Application L2 (avec Kickstart si démarrage)
            if (speed2 == 0) {
              if (id(fan_2).state) id(fan_2).turn_off().perform();
            } else {
              if (!id(fan_2).state) {
                 // Kickstart
                 id(fan_2).turn_on().set_speed(50).perform();
                 delay(1000);
              }
              id(fan_2).turn_on().set_speed(speed2).perform();
            }
          }
