esphome:
  name: esp-fan
  friendly_name: esp-fan

esp32:
  board: esp32-s3-devkitc-1
  framework:
    type: esp-idf

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "GXuwx9Eh7Jr9+Ftj90jDXDfkYIWw9fQ77Si5HCQ94m8="

ota:
  - platform: esphome

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Esp-Fan Fallback Hotspot"
    password: !secret wifi_password

captive_portal:

# Interface web optionnelle
web_server:
  port: 80

# Sortie PWM pour contrôler la vitesse
output:
  - platform: ledc
    pin: GPIO6
    id: fan_pwm_output
    frequency: 25000 Hz  # Fréquence PWM optimale pour Arctic P12 Pro (21-28 kHz)
    min_power: 0.0
    max_power: 1.0
    # Décommentez la ligne suivante si vous utilisez un transistor NPN (signal inversé)
    # inverted: true

# Capteur de vitesse (tachymètre)
sensor:
  - platform: pulse_counter
    pin: 
      number: GPIO4
      mode:
        input: true
        pullup: true
    name: "Vitesse Ventilateur"
    unit_of_measurement: 'RPM'
    accuracy_decimals: 0
    filters:
      # Le pulse_counter compte en pulses/min
      # Les ventilateurs 4 fils font 2 impulsions par tour
      # RPM = pulses/min / 2
      - lambda: return x / 2.0;
    count_mode:
      rising_edge: INCREMENT
      falling_edge: DISABLE
    update_interval: 3s
    id: fan_speed
  
  # Capteur de température interne ESP32
  - platform: internal_temperature
    name: "Température ESP32"
    update_interval: 60s
    id: esp32_temp

  # Capteur DHT22 pour température et humidité
  - platform: dht
    pin: GPIO7  # Changez ce GPIO selon votre câblage
    model: DHT22
    temperature:
      name: "Température Ambiante"
      id: temp_ambient
      on_value:
        then:
          - if:
              condition:
                switch.is_on: auto_mode
              then:
                - lambda: |-
                    // Automation: ajustement vitesse selon température (seulement si mode auto activé)
                    float temp = id(temp_ambient).state;
                    int speed = 0;
                    
                    if (temp < 20) {
                      speed = 0;  // Ventilateur éteint
                    } else if (temp < 25) {
                      speed = 25;  // Vitesse minimale
                    } else if (temp < 30) {
                      speed = 50;  // Vitesse moyenne
                    } else if (temp < 35) {
                      speed = 75;  // Vitesse élevée
                    } else {
                      speed = 100;  // Vitesse maximale
                    }
                    
                    // Applique la nouvelle vitesse
                    if (speed == 0) {
                      auto call = id(arctic_fan).turn_off();
                      call.perform();
                    } else {
                      auto call = id(arctic_fan).turn_on();
                      call.set_speed(speed);
                      call.perform();
                    }
                    
                    ESP_LOGI("climate", "Mode AUTO - Température: %.1f°C → Ventilateur: %d%%", temp, speed);
    humidity:
      name: "Humidité Ambiante"
      id: humidity_ambient
    update_interval: 30s  # Mise à jour toutes les 30 secondes

# Ventilateur
fan:
  - platform: speed
    output: fan_pwm_output
    name: "Ventilateur Arctic Pro"
    id: arctic_fan
    speed_count: 100

# Slider pour contrôle manuel de la vitesse (0-100%)
# Synchronisé avec l'état réel du ventilateur
number:
  - platform: template
    name: "Vitesse Manuelle"
    id: manual_speed
    min_value: 0
    max_value: 100
    step: 5
    optimistic: false  # Le slider reflète l'état réel du ventilateur
    unit_of_measurement: "%"
    mode: slider
    icon: "mdi:fan"
    set_action:
      then:
        - if:
            condition:
              lambda: 'return x == 0;'
            then:
              - fan.turn_off: arctic_fan
              - logger.log: "Ventilateur éteint"
            else:
              - fan.turn_on:
                  id: arctic_fan
                  speed: !lambda 'return int(x);'
              - logger.log:
                  format: "Ventilateur à %.0f%%"
                  args: ['x']
    lambda: |-
      if (id(arctic_fan).state) {
        return id(arctic_fan).speed;
      } else {
        return 0;
      }

# Switch pour activer/désactiver le contrôle automatique
switch:
  - platform: template
    name: "Mode Automatique"
    id: auto_mode
    optimistic: true
    restore_mode: RESTORE_DEFAULT_ON
    icon: "mdi:thermostat-auto"
    turn_on_action:
      - logger.log: "Mode automatique activé - Contrôle par température"
    turn_off_action:
      - logger.log: "Mode automatique désactivé - Contrôle manuel"